# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e0e0264062489e2d758b299f1b29eaec36c8ccd9cb617973043ab8e14f85f146b2506b65a07359aa5d3bfa103b20d1447c59098c117feb9f8871c86ea267c95d

test:
  secret_key_base: bbdd8fa0da7bfe8ed9d8fd1d2d6773b1e411a71642727acfe5bc1a04eeb57f6666dee5f30eab4a8630de86904e5194fd3ae380b079bc9bd323275dfcf1a4f0b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
